### ISSUE TITLE
Experience-to-level off by one in unspecified circumstances

### ISSUE THREAD

**Issue by ldionmarcil** [ldionmarcil/OSRSHelper#18]
ie 105488 in app, 105489 in game

**Comment by TyMarc** [comment]
Comparaison des fichiers realnumbers.txt et OSRSHELPER.TXT
***** realnumbers.txt
  84:  3258594
  85:  3597792
  86:  3972294
***** OSRSHELPER.TXT
  84:  3258594
  85:  3597791
  86:  3972294
*****

***** realnumbers.txt
  88:  4842295
  89:  5346332
  90:  5902831
  91:  6517253
***** OSRSHELPER.TXT
  88:  4842295
  89:  5346331
  90:  5902830
  91:  6517253
*****

***** realnumbers.txt
  94:  8771558
  95:  9684577
  96:  10692629
  97:  11805606
  98:  13034431
***** OSRSHELPER.TXT
  94:  8771558
  95:  9684576
  96:  10692628
  97:  11805605
  98:  13034430
*****
